### ISSUE TITLE
No privacy policy on web?

### ISSUE THREAD

**Issue by thetayloredman** [Schotsl/Uwuifier-client#11]
The website doesn't have a publicly-visible privacy policy, and I can see you are using Google Analytics. This is illigal to collect user data without a proper privacy policy.

Evidence of Google Analytics:
![Evidence](https://badboyhalocat.tk/i/24.png)

*Edit*: Embedded image instead of URL

**Comment by thetayloredman** [comment]
Alright, I added you, `BadBoyHaloCat#1826`

**Comment by Schotsl** [comment]
Fixed this by adding Plausible Analytics and removing Google Analytics since I really didn't want an annoying pop-up for a simple / fun site! :)
