### ISSUE TITLE
Upgrade to Vue 3

### ISSUE THREAD

**Issue by dbrxnds** [Schotsl/Uwuifier-client#2]
Hi, 

It would be nice if this were written in Vue 3 rather than 2.6.

**Comment by Schotsl** [comment]
I rewrote the codebase to v3 and pushed, I don't think it has a single benefit for us but sometimes you gotta live a little.

**Comment by dbrxnds** [comment]
I was very sad to you did not actually rewrite to Vue 3. As the package.json still shows 2.6.11

**Comment by Schotsl** [comment]
Oops, I've decided we should wait for Vue 3 to mature before switching since it seems like alot of effort right now I'd like to see more documentation ;)
