### ISSUE TITLE
ReactJS based version

### ISSUE THREAD

**Issue by dbrxnds** [Schotsl/Uwuifier-client#3]
Hi,

It would be nice if there were a [ReactJS](https://reactjs.org/) documentation available.

**Comment by Schotsl** [comment]
I feel like this would be the perfect task for @iDavidB

**Comment by Schotsl** [comment]
@iDavidB progress?

**Comment by dbrxnds** [comment]
Finished. Never released.

**Comment by Schotsl** [comment]
Should I close this branch or are you gonna release?
